version: 2
updates:
  - package-ecosystem: "npm"       # Pour Node.js; pour Python => "pip"
    directory: "/"                 # Chemin du package.json
    schedule:
      interval: "daily"            # Fr√©quence du scan
